name: Storybook Build and Deploy

on:
  push:
    branches-ignore:
      - release/**

jobs:
  build-and-deploy:
    name: build-and-deploy storybook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploy storybook
        run: yarn deploy
        with:
          branch: gh-pages
          folder: storybook-static
