name: Storybook Build and Deploy

on:
  push:
    paths:
      - '**.stories.tsx'
    branches-ignore:
      - release/**

jobs:
  build-and-deploy:
    name: build-and-deploy storybook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install and Build
        run: |
          yarn install
          yarn build-storybook
      - name: deploy storybook
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          branch: gh-pages
          folder: storybook-static