name: Storybook Build and Deploy

on:
  push:
    branches-ignore:
      - release/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploy storybook
        uses: JamesIves/github-pages-deploy-action@4.1.0
        run: yarn deploy
        with:
          branch: gh-pages
          folder: storybook-static
