name: Open issues
on:
  issues:
    types:
      - reopened
      - opened

jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@master
        with:
          project: proeco/proeco-client
          column: Open
          repo-token: ${{ secrets.ISSUE_OPEN_TOKEN }}
