name: Open issues

on:
  issues:
    types:
      - reopened
      - opened

jobs:
  move-assigned-card:
    runs-on: ubuntu-18.04
    steps:
      - uses: alex-page/github-project-automation-plus@5bcba1c1c091a222584d10913e5c060d32c44044
        with:
          project: Proeco Dev
          column: 🧐 Open
          repo-token: ${{ secrets.ISSUE_OPEN_TOKEN }}
